codecov:
  require_ci_to_pass: yes
  
ignore:
  - "tests/**/*"
  - "Qt/**/*"
  - "3rdparty/**/*"
  - "src/shared/**/*"
  - "src/editor/**/*"
  - "src/converter/main_window.*"
  - "src/converter/main.*"
  - "src/converter/podofo_paintdevice.*"
  - "src/converter/progress.*"
  - "src/converter/syntax.*"
