version = 1
SPDX-PackageName = "markdown-tools-page"
SPDX-PackageSupplier = "Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-PackageDownloadLocation = "https://igormironchik.github.io/markdown-tools/"

[[annotations]]
path = ["css/**", "js/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-present Jędrzej Chałubek"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["img/**", "index.html"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Igor Mironchik <igor.mironchik@gmail.com>"
SPDX-License-Identifier = "GPL-3.0-or-later"
