rm -rf 3rdparty/Skia/agents
rm -rf 3rdparty/Skia/bazel
rm -rf 3rdparty/Skia/bench
rm -rf 3rdparty/Skia/build_overrides
rm -rf 3rdparty/Skia/client_utils
rm -rf 3rdparty/Skia/demos.skia.org
rm -rf 3rdparty/Skia/dm
rm -rf 3rdparty/Skia/example
rm -rf 3rdparty/Skia/fuzz
rm -rf 3rdparty/Skia/gm
rm -rf 3rdparty/Skia/infra
rm -rf 3rdparty/Skia/platform_tools
rm -rf 3rdparty/Skia/relnotes
rm -rf 3rdparty/Skia/resources
rm -rf 3rdparty/Skia/rust
rm -rf 3rdparty/Skia/site
rm -rf 3rdparty/Skia/specs
rm -rf 3rdparty/Skia/toolchain
rm -rf 3rdparty/Skia/third_party/angle2
rm -rf 3rdparty/Skia/third_party/brotli
rm -rf 3rdparty/Skia/third_party/cpu-features
rm -rf 3rdparty/Skia/third_party/d3d12allocator
rm -rf 3rdparty/Skia/third_party/delaunator
rm -rf 3rdparty/Skia/third_party/etc1
rm -rf 3rdparty/Skia/third_party/highway
rm -rf 3rdparty/Skia/third_party/icu4x
rm -rf 3rdparty/Skia/third_party/icu_bidi
rm -rf 3rdparty/Skia/third_party/imgui
rm -rf 3rdparty/Skia/third_party/libavif
rm -rf 3rdparty/Skia/third_party/libgav1
rm -rf 3rdparty/Skia/third_party/libgrapheme
rm -rf 3rdparty/Skia/third_party/libjxl
rm -rf 3rdparty/Skia/third_party/libyuv
rm -rf 3rdparty/Skia/third_party/lua
rm -rf 3rdparty/Skia/third_party/native_app_glue
rm -rf 3rdparty/Skia/third_party/oboe
rm -rf 3rdparty/Skia/third_party/perfetto
rm -rf 3rdparty/Skia/third_party/spirv-cross
rm -rf 3rdparty/Skia/third_party/vello
rm -rf 3rdparty/Skia/third_party/externals/abseil-cpp
rm -rf 3rdparty/Skia/third_party/externals/angle2
rm -rf 3rdparty/Skia/third_party/externals/brotli
rm -rf 3rdparty/Skia/third_party/externals/d3d12allocator
rm -rf 3rdparty/Skia/third_party/externals/dawn
rm -rf 3rdparty/Skia/third_party/externals/delaunator-cpp
rm -rf 3rdparty/Skia/third_party/externals/egl-registry
rm -rf 3rdparty/Skia/third_party/externals/emsdk
rm -rf 3rdparty/Skia/third_party/externals/freetype
rm -rf 3rdparty/Skia/third_party/externals/glslang
rm -rf 3rdparty/Skia/third_party/externals/highway
rm -rf 3rdparty/Skia/third_party/externals/icu4x
rm -rf 3rdparty/Skia/third_party/externals/imgui
rm -rf 3rdparty/Skia/third_party/externals/jinja2
rm -rf 3rdparty/Skia/third_party/externals/libavif
rm -rf 3rdparty/Skia/third_party/externals/libgav1
rm -rf 3rdparty/Skia/third_party/externals/libgrapheme
rm -rf 3rdparty/Skia/third_party/externals/libjxl
rm -rf 3rdparty/Skia/third_party/externals/libyuv
rm -rf 3rdparty/Skia/third_party/externals/markupsafe
rm -rf 3rdparty/Skia/third_party/externals/oboe
rm -rf 3rdparty/Skia/third_party/externals/opengl-registry
rm -rf 3rdparty/Skia/third_party/externals/partition_alloc
rm -rf 3rdparty/Skia/third_party/externals/perfetto
rm -rf 3rdparty/Skia/third_party/externals/spirv-cross
rm -rf 3rdparty/Skia/third_party/externals/spirv-headers
rm -rf 3rdparty/Skia/third_party/externals/spirv-tools
rm -rf 3rdparty/Skia/third_party/externals/swiftshader
rm -rf 3rdparty/Skia/third_party/externals/unicodetools
rm -rf 3rdparty/Skia/third_party/externals/vello
rm -rf 3rdparty/Skia/third_party/externals/vulkan-deps
rm -rf 3rdparty/Skia/third_party/externals/vulkan-headers
rm -rf 3rdparty/Skia/third_party/externals/vulkanmemoryallocator
rm -rf 3rdparty/Skia/third_party/externals/vulkan-tools
rm -rf 3rdparty/Skia/third_party/externals/vulkan-utility-libraries
rm -rf 3rdparty/Skia/third_party/externals/webgpu-headers
