Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@same'

Options:
 test-before-installing: true
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']

 # exclude stuff from cppcheck that takes too long
 cppcheck-ignore-files:
  - 'src/lib/abstracthighlighter.cpp'

 # skip test files that are invalid by design
 xml-validate-ignore:
  - 'autotests/input/highlight.xml'
  - 'autotests/input/syntax/brokenlang.xml'
  - 'data/generators/xslt.base.xml'
